language: node_js
node_js:
- 10

script:
- chmod 600 ./deploy_id_rsa.pem
- ssh-keyscan -H 89.208.199.114 >> ~/.ssh/known_hosts
- scp -i ./deploy_id_rsa.pem ./index.html ubuntu@89.208.199.114:/home/ubuntu/www
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_32509143ff02_key -iv $encrypted_32509143ff02_iv
  -in travis_id_rsa.enc -out ./travis_id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./travis_id_rsa
- echo -e "Host $DEPLOYMENT_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./travis_id_rsa

before_script:
- npm install

script:
- npm run build
- scp -i ./travis_id_rsa -r ./docker-compose.yml ./public sadislands@$DEPLOYMENT_IP_ADDRESS:/home/sadislands/f/2019_1_The-Recovery-Team
