export enum wsActions {
  SET_CHAT_MESSAGE = 'SET_CHAT_MESSAGE',
  INIT_CHAT_MESSAGE = 'INIT_CHAT_MESSAGE',
  SET_CHAT_SESSION = 'SET_CHAT_SESSION',
  SET_CHAT_GLOBAL_MESSAGES = 'SET_CHAT_GLOBAL_MESSAGES',
  INIT_CHAT_GLOBAL_MESSAGES = 'INIT_CHAT_GLOBAL_MESSAGES',
}
