export enum CurPage {
  START = 'START',
  SIGNIN = 'SIGNIN',
  SIGNUP = 'SIGNUP',
  PROFILE = 'PROFILE',
  EDIT_PROFILE = 'EDIT_PROFILE',
  RULES = 'RULES',
  LEADERS = 'LEADERS',
  ABOUT = 'ABOUT',
}
